DROP TABLE IF EXISTS inventory.items CASCADE;

DROP TABLE IF EXISTS audit.audit_log CASCADE;

DROP TABLE IF EXISTS documents.files CASCADE;

DROP TABLE IF EXISTS core.outbox_events CASCADE;
DROP TABLE IF EXISTS core.user_roles CASCADE;
DROP TABLE IF EXISTS core.role_permissions CASCADE;
DROP TABLE IF EXISTS core.permissions CASCADE;
DROP TABLE IF EXISTS core.roles CASCADE;
DROP TABLE IF EXISTS core.tenant_users CASCADE;

DROP TABLE IF EXISTS control.tenant_limits CASCADE;
DROP TABLE IF EXISTS control.tenant_enabled_modules CASCADE;
DROP TABLE IF EXISTS control.tenant_subscriptions CASCADE;
DROP TABLE IF EXISTS control.plan_modules CASCADE;
DROP TABLE IF EXISTS control.plans CASCADE;
DROP TABLE IF EXISTS control.modules CASCADE;
DROP TABLE IF EXISTS control.tenants CASCADE;

DROP FUNCTION IF EXISTS core.current_tenant_id();

DROP SCHEMA IF EXISTS reports CASCADE;
DROP SCHEMA IF EXISTS accounting CASCADE;
DROP SCHEMA IF EXISTS purchase CASCADE;
DROP SCHEMA IF EXISTS sales CASCADE;
DROP SCHEMA IF EXISTS inventory CASCADE;
DROP SCHEMA IF EXISTS workflow CASCADE;
DROP SCHEMA IF EXISTS audit CASCADE;
DROP SCHEMA IF EXISTS documents CASCADE;
DROP SCHEMA IF EXISTS core CASCADE;
DROP SCHEMA IF EXISTS control CASCADE;
